studySpec:
  metrics:
  - metricId: val_accuracy
    goal: MAXIMIZE
  parameters:
  - parameterId: fine_tune_lr
    doubleValueSpec:
      minValue: 0.00001
      maxValue: 0.001
    scaleType: UNIT_LOG_SCALE
  - parameterId: dropout_rate
    doubleValueSpec:
      minValue: 0.2
      maxValue: 0.5
    scaleType: UNIT_LINEAR_SCALE
  - parameterId: unfreeze_layers
    discreteValueSpec:
      values: [20, 60, 100]
trialJobSpec:
  workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
      acceleratorType: NVIDIA_TESLA_T4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      # We will update this imageUri in the next step
      imageUri: us-central1-docker.pkg.dev/red-context-466220-s0/dog-breed-repo/mle-dog-classifier:6146086
      args:
      - "--fine_tune_lr=$(study.trial.parameter.fine_tune_lr)"
      - "--dropout_rate=$(study.trial.parameter.dropout_rate)"
      - "--unfreeze_layers=$(study.trial.parameter.unfreeze_layers)"